# Default values for social-finance
# This is a YAML-formatted file.

replicaCount:
  backend: 2
  frontend: 2

image:
  backend:
    repository: your-registry/social-finance-backend
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  frontend:
    repository: your-registry/social-finance-frontend
    tag: "1.0.0"
    pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  backend:
    port: 8000
    targetPort: 8000
  frontend:
    port: 3000
    targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: social-finance.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix
  tls:
    - secretName: social-finance-tls
      hosts:
        - social-finance.yourdomain.com

resources:
  backend:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  frontend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

autoscaling:
  backend:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  frontend:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  enabled: true
  auth:
    postgresPassword: "your-postgres-password"
    database: "social_finance"
  primary:
    persistence:
      enabled: true
      size: 10Gi
  service:
    type: ClusterIP

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 5Gi
  service:
    type: ClusterIP

stripe:
  secretKey: "sk_test_..."
  publishableKey: "pk_test_..."
  webhookSecret: "whsec_..."

jwt:
  secretKey: "your-jwt-secret-key-change-in-production"
  algorithm: "HS256"
  accessTokenExpireMinutes: 30

upload:
  maxFileSize: 10485760  # 10MB
  uploadDir: "./uploads"

cors:
  allowedOrigins:
    - "https://social-finance.yourdomain.com"
    - "http://localhost:3000" 