apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "social-finance.fullname" . }}-backend
  labels:
    {{- include "social-finance.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      {{- include "social-finance.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "social-finance.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "social-finance.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgresql.auth.database }}:{{ .Values.postgresql.auth.postgresPassword }}@{{ include "social-finance.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
            - name: REDIS_URL
              value: "redis://{{ include "social-finance.fullname" . }}-redis-master:6379"
            - name: SECRET_KEY
              value: {{ .Values.jwt.secretKey | quote }}
            - name: ALGORITHM
              value: {{ .Values.jwt.algorithm | quote }}
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: {{ .Values.jwt.accessTokenExpireMinutes | quote }}
            - name: STRIPE_SECRET_KEY
              value: {{ .Values.stripe.secretKey | quote }}
            - name: STRIPE_PUBLISHABLE_KEY
              value: {{ .Values.stripe.publishableKey | quote }}
            - name: STRIPE_WEBHOOK_SECRET
              value: {{ .Values.stripe.webhookSecret | quote }}
            - name: UPLOAD_DIR
              value: {{ .Values.upload.uploadDir | quote }}
            - name: MAX_FILE_SIZE
              value: {{ .Values.upload.maxFileSize | quote }}
            - name: ALLOWED_ORIGINS
              value: {{ join "," .Values.cors.allowedOrigins | quote }}
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 