apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-finance.fullname" . }}-backend
  labels:
    {{- include "social-finance.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "social-finance.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend 