apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "social-finance.fullname" . }}-postgres-pvc
  labels:
    {{- include "social-finance.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }} 